### ISSUE TITLE
Add Forfeit Functionality

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#10]
### Description
Sometimes teams need to forfeit because they do not have enough players, or  other reasons, but they wish to still play the games. We want to mark the forfeit for a win for the other team, but still record player stats.

### Tasks
- [ ] Add a forfeit checkmark for both teams to gameInfo form.
- [ ] Change query that uploads game info to take in handle forfeit by giving the other team win even if they lost based on score.
- [ ] Add forfeit column(s) to games table
- [ ] Track when forfeit occurs in eventLog

### Additional Notes
- Discuss how to handle if both teams do not have appropriate number of players.
- Deadline: May 10, 2024
