### ISSUE TITLE
Integrate MailChimp Functionality

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#11]
### Description
Currently all emails are sent from mailchimp account for league information. In Mailchimp they need to make each Campagin by hand. Also, password resets are coming from a personal email address. We want to make an easy dynamic method for quick group and individual messages.

### Tasks
- [ ] Get access to mailchimpMarketing api key for user
- [ ] Get Mandrill/mailchimp plan for user, or find another method for individual transactional emails. (payments, password resets)
- [ ] Create mailchimp module for reusable functions.
- [ ] Save email Template background as mcusercontent file for easy use
- [ ] Figure out how to have create dynamic campaign distribution lists based on certain criteria (Team, League, Staff, Captains)
- [ ] Learn SMS functionality and implement into campaigns

### Additional Notes
- Deadline: May 10, 2024
