### ISSUE TITLE
Add Break Countdown Timer

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#12]
### Description
Between periods the players get a break, but to keep the games going and on time these breaks need to stay within a specific amount of time. Need to add timer so that scorekeepers are kept on track with these breaks to ensure game ends at correct time.

### Tasks
- [ ] Add period end time tracking in database table games
- [ ] When period ends send end time to database
- [ ] Add popup of break timer
- [ ] Ensure that the user can still access all features within the game during the break
- [ ] Ensure user can start next period before break is over.
- [ ] Add alert to ensure scorekeeper is aware break is over.
- [ ] Have server check remaining time until required end time, and if there is not enough time, first reduce remaining breaks accordingly, then reduce remaining periods accordingly.

### Additional Notes
- Possibly add a notification that game has not started by required start time
- Deadline: May 10, 2024
