### ISSUE TITLE
Yellow and Red Card Functionality

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#13]
### Description
Need to complete tracking and notation for yellow and red cards for summer competitive games.

### Tasks
- [x] Track yellow and Red Cards in log.
- [ ] Add identifiers on player indicating if they received a yellow or red card.
- [ ] Direct reds add form explaining what happened, and suggested suspension.
- [ ] If double yellow automatically mark red, note that it was a double yellow red, and apply default suspension.
- [ ] Have an alert on player if they are currently suspended.
- [ ] Do not allow stats for suspended player.
- [ ] Add ability for league manage to remove suspension.

### Additional Notes
- Possibly consider if yellow cards should have notes.
- Deadline: May 10, 2024
