### ISSUE TITLE
Period and Clock time adjustments

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#14]
### Description
Sometimes a scorekeeper may need to change the period number or remaining time in period. Need to provide functionality.

### Tasks
- [ ] Add period time and period number inputs to gameInfo form
- [ ] Add checkbox indicating desire to change these, so that they will not be changed if they change a different GameInfo item.
- [ ] Hide period time and period number inputs unless checkbox is checked.
- [ ] Ask if user is sure, and let them know the clock will be stopped if it is currently running.

### Additional Notes
- Deadline: May 10, 2024

**Comment by forslundscott** [comment]
period adjustment is done, trying to brainstorm how to do the clock so that it will know when the person is trying to change it.
