### ISSUE TITLE
Role Assignment

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#16]
### Description
Currently all role creation and assignment is done by admin on back end. We need to create a form to add new roles, and change assigned roles for users and staff.

### Tasks
- [ ] Have a button inside league logo only league manager and admin can see and use.
- [ ] Create page that lists all users that you can select users to add or remove roles.
- [ ] Create search by name in the role change page.
- [ ] In role selection list have option to create new role, that requires a description of what the role has access to
- [ ] When new role is created have an alert go to server admin to design role as specified

### Additional Notes
- Consider sub roles or role templates that can be used amongst sever similar situations.
- Start with staff, currently app is not ready for players, captains, coaches or spectators.
- Dependent on #20
- Deadline: May 3, 2024

**Comment by forslundscott** [comment]
Made role add in user page.
