### ISSUE TITLE
Nutmeg Tracking

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#17]
### Description
A nutmeg in soccer is when a player puts the ball through another players legs and continues to have possession of the ball afterwards.

### Tasks
- [ ] Add nutmeg button to eventButtons
- [ ] When clicked popup list asking who was nutmeged
- [ ] Add nutmeg counts to standing data

### Additional Notes
- Any specific considerations or requirements for the migration.
- Deadline: TBD
