### ISSUE TITLE
Sub Request Functionality

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#18]
### Description
Sometimes a team captain is unable to find subs on their own for a game. Currently all requests go to league manager by email or text. We need to create a method to request through the app that will check a list of potential subs for availability to assist the manager.

### Tasks
- [ ] Add button on captain view of game for sub requests.
- [ ] Have form popup that asks how many subs (by gender if coed)
- [ ] Have server find best sub options, based on skill rating, league, availability.
- [ ] Either have the results go to league manager for review, allow captain to choose desired subs from suggestions, or automatically send requests to the top options.
- [ ] When sub request is received by sub allow them to accept or decline.
- [ ] If automatically sending requests, if sub declines, move on to next best option
- [ ] If manager or captain chose the subs, then send notification to them indicating sub declined and give recommendation list again for them to select another.
- [ ] If sub accepts add them to the rsvp page specific for that game, so both the captain can see the number of rsvps, and sub can have the game added to their calendar.

### Additional Notes
- Deadline: TDB
