### ISSUE TITLE
Complete Role Authentation

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#20]
### Description
Need to finish creating role storage and authentication on the server for routes and views.

### Tasks
- [ ] Store user roles in passport user.
- [ ] Create middleware to check if user has required role to access route
- [ ] Adjust views not display if user does not have proper roles for sensitive information
- [ ] Adjust views to not provide links, or submit capabilities for things they do not have access to.

### Additional Notes
- There are multiple other issues that will be dependent on this one.
- Deadline: May 10, 2024
