### ISSUE TITLE
Player added as both sub and rostered player

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#23]
Sometimes a scorekeeper adds a player as both a sub and rostered player. This causes issues for tracking how many times a sub has played. Also, a player should only be added as rostered once they have paid the fee.

### Tasks Needed to remedy
- [ ] If player is rostered already prevent adding of them as sub
- [ ] Add checkbox to adding rostered player ensuring fee paid
- [ ] If a sub pays the fee, add option to removed them from sub list and add as rostered player
