### ISSUE TITLE
New Game Functionality

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#26]
### Tasks to Complete

- [x] Add button in games list to add new game
- [x] Create new player form
- [x] Form to request league name
- [x] Team name dropdowns
- [x] Date and time selectors
- [x] Location and field selectors
- [ ] If Team Score only game allow adding score and completing game right away
- [ ] Scorekeeper selector
- [ ] Ref selector?
