### ISSUE TITLE
Sportsmanship Voting

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#29]
#### Description
To encourage players to have a quality and friendly attitude during games, and idea has come to light for sportsmanship voting and rewarding.

#### Tasks
- [ ] Player photos are essential for users to know who they are voting for.
- [ ] Tie into Mailchimp to send emails to teams.
- [ ] Automate email sent to each rostered player asking to vote or rank sportsmanship of players on the other team.

#### Other considerations
- When app is available to players, allow them to vote in the app
- Possible reward of discount for winning sportsmanship player
- Possible if multiple players on the same team are top 5 to have a team reward
