### ISSUE TITLE
Build Schedule Generator

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#7]
### Description
Currently Schedule making is done using external sites that do not have access to team or player data for an accurate schedule creation, while avoiding schedule conflicts between teams and players, also to automatically match based on historical standing data.

### Tasks
- [x] Create Random Schedule Generator that takes in two variables: 1. List of teams and 2. Number of games per teams
- [x] Add playoff functionality, will automatically create playoff games if teams cannot play opponents an equal number of times
- [x] Have users be able to be made based on email at registration, before they create a password
- [x] Tie user email to player_team relational table
- [ ] Add functionality to ensure players that play on multiple teams will not have schedule conflicts
- [x] Add holiday's recognized by league for consideration
- [x] Add db table for all generated schedules, to allow user to create several and compare before committing to one.
- [x] Add player skill and experience ratings
- [x] Use cumulative player skill ratings to calculate team rating
- [x] Add team rating consideration for schedule generation.

### Additional Notes
- This is needed 1 week before games start.
- Deadline: May 3, 2024
