### ISSUE TITLE
Add Game Cancellation Functionality

### ISSUE THREAD

**Issue by forslundscott** [forslundscott/scorecardApp#9]
### Description
Sometimes games are called before game starts or during game for weather or other reasons. Need a button that can properly handle these situations.

### Tasks
- [x] Create function that will check what period the game is cancelled in. If before half game is fully replayed if after game is over. (Before or after end of second period for 3 period games)
- [x] If game is to be replayed it needs a special status or to be added to a special list so it is apparent that it needs to be rescheduled.
- [ ] Add button to gameData form to initiate cancellation. Have an "Are you sure" form pop up before committing is defaulted to "No"

### Additional Notes
- Need some way for games to stand out if they need to be rescheduled.
- Deadline: May 10, 2024
